export const initialSystemLimits = {
  maxDevicesLimit: 3,
  maxFileSizeValue: 500,
  maxFileSizeUnit: "MB",
  sessionTimeoutValue: 24,
  sessionTimeoutUnit: "Hours",
  defaultStorageUnit: "GB",
};

export const initialPlanTiers = [
  {
    slug: "free-trial",
    type: "Free Trial",
    title: "Free Trial",
    description: "Try everything free for 30 days with essential features.",
    badge: "30 Days Free",
    accentColor: "emerald",
    active: true,
  },
  {
    slug: "novice",
    type: "Novice",
    title: "Novice Vault",
    description: "1 TB secure storage for personal files and photos.",
    badge: "Personal",
    accentColor: "purple",
    active: true,
  },
  {
    slug: "professional",
    type: "Professional",
    title: "Professional",
    description:
      "Designed for creators and power users with priority speed and AI search.",
    badge: "Most Popular",
    accentColor: "rose",
    active: true,
  },
  {
    slug: "ultimate",
    type: "Ultimate",
    title: "Ultimate Enterprise",
    description:
      "Everything included with 15 TB storage for teams and total backup.",
    badge: "Best Value",
    accentColor: "sky",
    active: true,
  },
];

export const initialBillingPlans = [
  {
    id: "plan_freetrial_monthly",
    planTier: "Free Trial",
    period: "Monthly",
    amount: 0,
    currency: "INR",
    storage: 5368709120, // 5 GB
    active: true,
    version: "v1.0",
    description: "30-day free trial tier with 5 GB storage and full Ultimate features.",
  },
  {
    id: "plan_freetrial_yearly",
    planTier: "Free Trial",
    period: "Yearly",
    amount: 0,
    currency: "INR",
    storage: 5368709120, // 5 GB
    active: true,
    version: "v1.0",
    description: "Annual free trial tier with 5 GB storage and full Ultimate features.",
  },
  {
    id: "plan_novice_monthly",
    planTier: "Novice",
    period: "Monthly",
    amount: 199,
    currency: "INR",
    storage: 1099511627776, // 1 TB
    active: true,
    version: "v1.2",
    description: "1 TB secure storage for personal files and photos.",
  },
  {
    id: "plan_novice_yearly",
    planTier: "Novice",
    period: "Yearly",
    amount: 1999,
    currency: "INR",
    storage: 1099511627776, // 1 TB
    active: true,
    version: "v1.2",
    description: "1 TB secure storage billed annually (2 months free).",
  },
  {
    id: "plan_pro_monthly",
    planTier: "Professional",
    period: "Monthly",
    amount: 499,
    currency: "INR",
    storage: 5497558138880, // 5 TB
    active: true,
    version: "v2.0",
    description:
      "5 TB storage with priority speed, cloud linkage and integrations.",
  },
  {
    id: "plan_pro_yearly",
    planTier: "Professional",
    period: "Yearly",
    amount: 4999,
    currency: "INR",
    storage: 5497558138880, // 5 TB
    active: true,
    version: "v2.0",
    description:
      "5 TB storage billed annually with priority speed and linkage.",
  },
  {
    id: "plan_ultimate_monthly",
    planTier: "Ultimate",
    period: "Monthly",
    amount: 1199,
    currency: "INR",
    storage: 16492674416640, // 15 TB
    active: true,
    version: "v3.1",
    description:
      "15 TB power storage for teams, AI search and unlimited versioning.",
  },
  {
    id: "plan_ultimate_yearly",
    planTier: "Ultimate",
    period: "Yearly",
    amount: 11999,
    currency: "INR",
    storage: 16492674416640, // 15 TB
    active: true,
    version: "v3.1",
    description: "15 TB annual power tier for teams and total backup.",
  },
];

export const initialFeatures = [
  {
    id: "feat_secure_storage",
    key: "secure_storage",
    title: "Secure Vault Storage",
    description: "AES-256 encrypted cloud file vault storage.",
    category: "Storage",
    enabled: true,
  },
  {
    id: "feat_folder_upload",
    key: "folder_upload",
    title: "Folder Hierarchy Upload",
    description:
      "Upload entire directory trees while preserving folder structure.",
    category: "Storage",
    enabled: true,
  },
  {
    id: "feat_share_links",
    key: "share_links",
    title: "Public Share Links",
    description: "Generate shareable links with read and download access.",
    category: "Sharing",
    enabled: true,
  },
  {
    id: "feat_password_links",
    key: "password_links",
    title: "Password Protected Links",
    description: "Protect shared files with secret access passcodes.",
    category: "Security",
    enabled: true,
  },
  {
    id: "feat_expiring_links",
    key: "expiring_links",
    title: "Expiring Access Links",
    description: "Set self-destruct time limits on public file shares.",
    category: "Security",
    enabled: true,
  },
  {
    id: "feat_gdrive",
    key: "gdrive_sync",
    title: "Google Drive Integration",
    description: "Direct import and seamless sync with Google Drive accounts.",
    category: "Integrations",
    enabled: true,
  },
  {
    id: "feat_dropbox",
    key: "dropbox_sync",
    title: "Dropbox Integration",
    description: "Connect and sync files directly with Dropbox vaults.",
    category: "Integrations",
    enabled: true,
  },
  {
    id: "feat_github",
    key: "github_backup",
    title: "GitHub Repository Backup",
    description: "Automated snapshot backup of code repositories.",
    category: "Integrations",
    enabled: true,
  },
  {
    id: "feat_ai_search",
    key: "ai_search",
    title: "AI Semantic Search",
    description: "Natural language search across file contents and metadata.",
    category: "AI",
    enabled: true,
  },
  {
    id: "feat_priority_speed",
    key: "priority_speed",
    title: "Priority Upload Acceleration",
    description: "10x faster multi-part upload bandwidth pipes.",
    category: "Performance",
    enabled: true,
  },
  {
    id: "feat_version_history",
    key: "version_history",
    title: "Unlimited Version History",
    description: "Restore previous file revisions without auto-pruning.",
    category: "Storage",
    enabled: true,
  },
  {
    id: "feat_priority_support",
    key: "priority_support",
    title: "24/7 Priority Support",
    description: "Dedicated account support channel with SLA guarantee.",
    category: "Support",
    enabled: true,
  },
];

export const initialPlanTierFeatureConfigs = {
  "Free Trial": [
    "secure_storage",
    "folder_upload",
    "share_links",
    "password_links",
    "expiring_links",
    "gdrive_sync",
    "dropbox_sync",
    "github_backup",
    "ai_search",
    "priority_speed",
    "version_history",
    "priority_support",
  ],
  Novice: [
    "secure_storage",
    "folder_upload",
    "share_links",
    "password_links",
    "expiring_links",
  ],
  Professional: [
    "secure_storage",
    "folder_upload",
    "share_links",
    "password_links",
    "expiring_links",
    "gdrive_sync",
    "dropbox_sync",
    "ai_search",
    "priority_speed",
  ],
  Ultimate: [
    "secure_storage",
    "folder_upload",
    "share_links",
    "password_links",
    "expiring_links",
    "gdrive_sync",
    "dropbox_sync",
    "github_backup",
    "ai_search",
    "priority_speed",
    "version_history",
    "priority_support",
  ],
};

export const initialPlanTierRuleConfigs = {
  "Free Trial": {
    allowUpload: true,
    allowDownload: true,
    allowSharing: true,
    allowEdit: true,
    allowMove: true,
    allowCopy: true,
    allowDelete: true,
    maxConnectedDevices: 5,
    maxUploadSizeVal: 2,
    maxUploadSizeUnit: "GB",
    uploadSpeedMultiplier: "10x",
    deleteFilesAfterExpiry: "30 days",
    versionHistoryDays: "30",
  },
  Novice: {
    allowUpload: true,
    allowDownload: true,
    allowSharing: true,
    allowEdit: true,
    allowMove: true,
    allowCopy: true,
    allowDelete: true,
    maxConnectedDevices: 5,
    maxUploadSizeVal: 5,
    maxUploadSizeUnit: "GB",
    uploadSpeedMultiplier: "5x",
    deleteFilesAfterExpiry: "Never",
    versionHistoryDays: "90",
  },
  Professional: {
    allowUpload: true,
    allowDownload: true,
    allowSharing: true,
    allowEdit: true,
    allowMove: true,
    allowCopy: true,
    allowDelete: true,
    maxConnectedDevices: 10,
    maxUploadSizeVal: 10,
    maxUploadSizeUnit: "GB",
    uploadSpeedMultiplier: "10x",
    deleteFilesAfterExpiry: "Never",
    versionHistoryDays: "365",
  },
  Ultimate: {
    allowUpload: true,
    allowDownload: true,
    allowSharing: true,
    allowEdit: true,
    allowMove: true,
    allowCopy: true,
    allowDelete: true,
    maxConnectedDevices: 20,
    maxUploadSizeVal: 20,
    maxUploadSizeUnit: "GB",
    uploadSpeedMultiplier: "20x",
    deleteFilesAfterExpiry: "Never",
    versionHistoryDays: "Unlimited",
  },
};
